### ISSUE TITLE
How to upload a Draco compressed GLB model on Spoke.

### ISSUE THREAD

**Issue by KrutikPandya07** [mozilla/Spoke#1216]
Hey,
I am trying to upload a compressed glb file in my assets and its prompting this error, I tried uploading draco compression from blender as well as 3ds max but they both give the same error. 
![Screenshot 2022-02-08 162438](https://user-images.githubusercontent.com/76621501/152973509-3f6b6be1-6c23-41d6-aaa8-20b4eee39815.png)

How can I resolve this issue?

**Comment by RBOSAMIYA9** [comment]
I have also tried using Draco compressed models into spoke and ran into the same error, but after started using **blender hubs exporter** and doing  **import from blender** I am now able to use Draco compressed models in hubs.

**Comment by KrutikPandya07** [comment]
Ohhh greatt!! but how can I set up the scene, like spawn point and collisions, etc, will I have to define them in blender?

**Comment by RBOSAMIYA9** [comment]
@KrutikPandya07  Check out this [blender hubs exporter](https://github.com/MozillaReality/hubs-blender-exporter) and you can add all the hubs components into it from into blender itself.

You can watch video of jim to learn it  
https://www.youtube.com/watch?v=ldHwbnMMKVY

Things to keep in mind:
- Scenes exported from blender using blender hubs exporter can not be integrated inside spoke 
- You have to define nav mesh too so that you can walk and move around properly.

**Comment by KrutikPandya07** [comment]
Thankk you so much man!!
