### ISSUE TITLE
Uniform Scale in PropertiesPanel

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#250]
This would be very useful for Sketchfab models which often in the cm scale

**Comment by robertlong** [comment]
glTF [specifies its units as meters](https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#coordinate-system-and-units) some exporters are still outputting incorrect units but this should get better with time. However, perhaps these issues stem from users uploading FBX files to sketchfab with incorrect unit settings.

In Unity there is a [Scale Factor](https://docs.unity3d.com/Manual/FBXImporter-Model.html) property on model assets. This works well for file types with known units, but for people new to Unity (or myself) this often was incorrect when using the wrong export settings from Maya or other tools. Scale Factor also affects the scale of vertex attributes in addition to transforms.

My suggestion for this feature is something similar to Unity. We would add a numeric input (defaulting to 1.0) that applies the scale to the model's transforms and vertex attributes.

We may want to hold off on this until we get animations in so that we can test with animated models.

**Comment by robertlong** [comment]
Yeah, I think that lock button is my number one feature request for Spoke right now.

**Comment by gfodor** [comment]
yeah its basically the only rough patch left in the hello world workflow
