### ISSUE TITLE
Need a field to allow manual attribution for acquired content

### ISSUE THREAD

**Issue by j-conrad** [mozilla/Spoke#414]
The use case:  I grabbed a model from Sketchfab, but edited it myself (Blender, etc.). Now when I add that model to Spoke, it doesn't have automatic attribution so I need a place to enter that info before publishing.

**Comment by robertlong** [comment]
Here's my proposed spec for this:

We should add a collapsible `Attributions` section to the `Model`, `Video`, `Image`, and `Spawner` nodes. Inside this section would be the attribution fields. We'll need three fields: `Title`, `Author`, and `Url`. You should be able to add multiple attributions to a node. One possible design would be to add plus and minus icons to add/remove field sets.

The first item in this list should be prepopulated with the following:

- Models from Sketchfab already have the title, author, and url fields embedded in the glTF so pre-populate the attribution fields with this data. We could also disable the inputs for these if we wanted since we don't really want people to edit these.
- Models from Google Poly have this info in the assets panel. It looks like we aren't setting attributions when you place these models in the scene. I think it did in the past, we need to correct this and pre-populate these fields like we do with Sketchfab models.
- Uploaded models should first pull from the `asset.extras` section which will be there in Sketchfab models, then it should use the `asset.copyright` field for the author, and the file name without the file extension for the title. Leave the url blank if it's not available.
- Images shouldn't have attributions for now. We don't have a reliable way to source these.
- Videos should have attributions, I think they are returned from the youtube-dl API and probably in our media search API.
- Uploaded images and videos shouldn't have default attributions, the user will need to set them directly.

On export, gather up all the attributions as we are doing right now.

In Hubs, we'll need to correct the way that these attributions are rendered. In the redesign I am planning on tacking this with a scrollable list. But we may want to throw something together really quick if we need this sooner.

**Comment by j-conrad** [comment]
_"- Uploaded images and videos shouldn't have default attributions, the user will need to set them directly."_

If there's a place somwhere in Spoke to specify the Spoke account holder's info, we could auto-populate with that. This might break down if the model was taken from somewhere else though. 
Not sure how I feel about this the more I consider it. 🤷‍♂️
