### ISSUE TITLE
Make it easier to learn how to get out of multi-place mode

### ISSUE THREAD

**Issue by gfodor** [mozilla/Spoke#810]
Currently, when you spawn objects now you are always spawning multiple copies. The only way to exit right now is to hit ESC, which may be non-obvious for people. I suggest (either or both):

- Adding a tooltip on screen that's fairly prominent telling the user to type ESC to exit (probably similar to the cursor lock in terms of size/emphasis)

- Making it so RMB click exits placement mode. You'd probably still want RMB drag to orbit the camera, so we'd need to detect a click vs a drag.

**Comment by gfodor** [comment]
alternatively, we could make this explicit, by having two actions on the thumbnails, one button that places a single one and one that places multiple. could be hard to get right tho, and could just make things more confusing.

**Comment by robertlong** [comment]
Right click is probably the most intuitive, the few people on the team that I've observed tried that first. However it conflicts with flying / looking around. In games like Minecraft, your cursor is locked so they don't need the second mouse button to trigger fly mode. In the past we talked about binding fly mode to another key, but then I'm worried that the fly mode action will get lost. 

I think there are tradeoffs with each set of keybindings and we'll want to do some proper user testing and research on existing UX to figure out the best defaults. I don't think what we have now is quite right and we need to collect some data to figure out what's best.

**Comment by misslivirose** [comment]
The tool tip feels like it would be a good step forward - the ESC key feels easy enough to get out of the mode.

I also think that multi-placement might be best only for architecture kit elements.

**Comment by gfodor** [comment]
If its possible to accurately detect click vs click-and-drag on RMB, that may work if we wanted to do the RMB thing

**Comment by gfodor** [comment]
i think i agree that tagging kits as having this special behavior works too

**Comment by robertlong** [comment]
I agree, a more visible tooltip rather than just the controls in the bottom right seems like an improvement. We should at least show it for the first time. We could also move those controls to the top right to make them more visible.

Maybe we could move orbit mode off left click and make fly mode the default for left click? It'd make the mouse controls closer to Hubs and free up right click. Also we can still have orbit mode bound to another key.

And yeah, I think the multi-placement mode per source seems like a good thing to implement so I'll go ahead with that. Kits will be the only sources tagged with multi-placement.

**Comment by robertlong** [comment]
Nvm, making fly mode left click still makes it so you can't fly and place at the same time.

**Comment by robertlong** [comment]
I made Spoke cancel the current action on right click. I think that should make things a lot easier.
