### ISSUE TITLE
Remove Twitch from Spoke

### ISSUE THREAD

**Issue by blairmacintyre** [mozilla/Spoke#925]
If I go to the "twitch" pane (bottom of left column), a "loading..." box flashes briefly in the center pane and then goes away.  So I can't add twitch streams to rooms.

**Comment by gfodor** [comment]
twitch search unfortunately needs to be removed from spoke - we already removed it in hubs. twitch changed their API so it is no longer possible to do what we were doing.

**Comment by blairmacintyre** [comment]
Wait, what!?  We can't twitch at all?  Or just can't search?

**Comment by gfodor** [comment]
Twitches api no longer supports search

**Comment by blairmacintyre** [comment]
oh, ok, that's cool.  But, can I place twitch videos in a scene?  Or only paste?   If I know the URL

**Comment by robertlong** [comment]
I didn't know they removed search. I can remove it from Spoke. It looks like twitch streams work fine but they spawn as a link when you paste since there's no content type set for them. So you'll want to paste the url into a video node for now. I'll special case the twitch domain when pasting to spawn a video when I make a PR to remove twitch.
